# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\work_and_study\code\seed implantation\OmniNav\SRC\Modules\ElectromagneticNavigation\ElectromagneticNavigation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ElectromagneticNavigationClass(object):
    def setupUi(self, ElectromagneticNavigationClass):
        ElectromagneticNavigationClass.setObjectName("ElectromagneticNavigationClass")
        ElectromagneticNavigationClass.resize(258, 600)
        ElectromagneticNavigationClass.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"font: 700 9pt \"Microsoft YaHei UI\";\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(ElectromagneticNavigationClass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.module_layout = QtWidgets.QVBoxLayout()
        self.module_layout.setContentsMargins(-1, -1, -1, 0)
        self.module_layout.setSpacing(0)
        self.module_layout.setObjectName("module_layout")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        self.logo_label.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.module_layout.addWidget(self.logo_label)
        self.instro_sa = QtWidgets.QScrollArea(self.centralwidget)
        self.instro_sa.setAutoFillBackground(False)
        self.instro_sa.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.instro_sa.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.instro_sa.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.instro_sa.setWidgetResizable(True)
        self.instro_sa.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.instro_sa.setObjectName("instro_sa")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 254, 69))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.about_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about_btn.sizePolicy().hasHeightForWidth())
        self.about_btn.setSizePolicy(sizePolicy)
        self.about_btn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.about_btn.setObjectName("about_btn")
        self.verticalLayout_2.addWidget(self.about_btn)
        self.acknowledgement_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acknowledgement_btn.sizePolicy().hasHeightForWidth())
        self.acknowledgement_btn.setSizePolicy(sizePolicy)
        self.acknowledgement_btn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.acknowledgement_btn.setObjectName("acknowledgement_btn")
        self.verticalLayout_2.addWidget(self.acknowledgement_btn)
        self.instro_sa.setWidget(self.scrollAreaWidgetContents)
        self.module_layout.addWidget(self.instro_sa, 0, QtCore.Qt.AlignTop)
        self.module_layout.setStretch(0, 3)
        self.module_layout.setStretch(1, 7)
        self.verticalLayout.addLayout(self.module_layout)
        ElectromagneticNavigationClass.setCentralWidget(self.centralwidget)

        self.retranslateUi(ElectromagneticNavigationClass)
        QtCore.QMetaObject.connectSlotsByName(ElectromagneticNavigationClass)

    def retranslateUi(self, ElectromagneticNavigationClass):
        _translate = QtCore.QCoreApplication.translate
        ElectromagneticNavigationClass.setWindowTitle(_translate("ElectromagneticNavigationClass", "ElectromagneticNavigation"))
        self.logo_label.setText(_translate("ElectromagneticNavigationClass", "OmniNavigator"))
        self.about_btn.setText(_translate("ElectromagneticNavigationClass", "About"))
        self.acknowledgement_btn.setText(_translate("ElectromagneticNavigationClass", "Acknowledgement"))
